#!/usr/bin/env python
import click
import os
from gendo.CiGen import DockerfileGen, DIR, DIR_ROLE, ComposeGen, GitlabGen, AnsibleGen

@click.group()
def cli():
    """ЭТО УТИЛИТА ДЛЯ ГЕНЕРАЦИИ КОНФИГОВ (dockerfiles, docker-compose, gitlab-ci)"""
    
@cli.command()
def gen():
    """Генерирует файлы для деплоя и CI."""
    if not os.path.exists(DIR):
        os.makedirs(DIR)
    
    if not os.path.exists(DIR_ROLE):
        os.makedirs(DIR_ROLE)
    
    dockerfile = DockerfileGen()
    composefile = ComposeGen()
    cifile = GitlabGen()
    ansible = AnsibleGen()
    
    dockerfile.create_dockerfile()
    composefile.check_webserver()
    composefile.gen_compose_file()
    cifile.create_ci_file()
    ansible.gen_ansible_role()
        
cli()