#!/usr/bin/env python
import click
import os
from gendo.CiGen import DockerfileGen, DIR, GitlabGen

@click.group()
def cli():
    """ЭТО УТИЛИТА ДЛЯ ГЕНЕРАЦИИ КОНФИГОВ (dockerfiles, gitlab-ci)"""
    
@cli.command()
def gen():
    """Генерирует файлы для деплоя и CI."""
    if not os.path.exists(DIR):
        os.makedirs(DIR)
    
    dockerfile = DockerfileGen()
    cifile = GitlabGen()

    dockerfile.create_dockerfile()
    cifile.create_ci_file()

cli()